spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://vietnhat0351:1234@cluster0.16gi4od.mongodb.net/e-commerce-product-service?retryWrites=true&w=majority&appName=Cluster0
    redis:
      host: localhost
      port: 6379
server:
  port: 8081
springdoc:
  swagger-ui:
    oauth:
      client-id: e-commerce-backend
      client-secret: zneg8gw1cxIzcGt3EIS043cmTYdikYIg
    path: /api/v2/products/api-docs
  api-docs:
    path: /api/v2/products/v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}

feign:
  client:
    order-service:
      url: http://localhost:9191/api/v1/orders

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-southeast-1

management:
  endpoints:
    web:
      exposure:
        include: "*"


