spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: lb://order-service
            predicates:
              - Path=/api/v1/orders/**
          - id: order-service-v2
            uri: lb://order-service
            predicates:
              - Path=/api/v2/orders/**

#          - id: websocket-sockjs-route
#            uri: lb://order-service
#            predicates:
#              - Path=/ws/info/**
#          - id: websocket_route
#            uri: lb://order-service
#            predicates:
#              - Path=/ws/**

#          - id: websocket_route
#            uri: lb://order-service
#            predicates:
#              - Path=/ws/**
#            filters:
#              - RewritePath=/ws/(?<segment>.*), /${segment}
#              - SetPath=/ws/${segment}
#              - SetHttpHeader=X-Forwarded-Proto,https
#              - name: WebSocket
#                args:
#                  ws-uri: "ws://localhost:9191/ws"

          - id: product-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/products/**
          - id: product-service-v2
            uri: lb://product-service
            predicates:
              - Path=/api/v2/products/**
          - id: storage-service
            uri: lb://product-service
            predicates:
              - Path=/api/v1/storage/**

          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/v1/users/**
          - id: user-service-v2
            uri: lb://user-service
            predicates:
              - Path=/api/v2/users/**

          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/v1/payment/**
          - id: payment-service-v2
            uri: lb://payment-service
            predicates:
              - Path=/api/v2/payment/**
server:
  port: 9191
  http2:
    enabled: false
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/discovery/eureka/
